server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://132.232.190.138:3306/xing_mp?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 123456

#自定义配置
resources:
    midpHost: 1.1.1.1

#jwt配置
jwt:
    EXPIRATIONTIME: 1000
    SECRET: OHAHAHAHA
